//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5472 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.DeliveryPrintService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeliveryPrintServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DeliveryPrintService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private myheader myheaderValueField;
        
        private System.Threading.SendOrPostCallback GetNoKdTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpKdFsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealseLockuserOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealseLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrintGroupByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrintPartOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderInfo2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderInfoPartOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetkucunOperationCompleted;
        
        private System.Threading.SendOrPostCallback kucunOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetorderNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderDeliveryPrintStateNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback DispatchListsInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDeliveryNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByDeliveryNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeupinhdOperationCompleted;
        
        private System.Threading.SendOrPostCallback RUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHdNameAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrintNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTuanNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWenTiDanOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpWTdanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHuiZongOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckMergerOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DeliveryPrintService() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.柠檬绿茶团购打印_DeliveryPrintService_DeliveryPrintService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public myheader myheaderValue {
            get {
                return this.myheaderValueField;
            }
            set {
                this.myheaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNoKdTableCompletedEventHandler GetNoKdTableCompleted;
        
        /// <remarks/>
        public event UpKdFsCompletedEventHandler UpKdFsCompleted;
        
        /// <remarks/>
        public event RealseLockuserCompletedEventHandler RealseLockuserCompleted;
        
        /// <remarks/>
        public event RealseLockCompletedEventHandler RealseLockCompleted;
        
        /// <remarks/>
        public event GetPrintGroupByCompletedEventHandler GetPrintGroupByCompleted;
        
        /// <remarks/>
        public event GetPrintPartCompletedEventHandler GetPrintPartCompleted;
        
        /// <remarks/>
        public event GetOrderInfo2CompletedEventHandler GetOrderInfo2Completed;
        
        /// <remarks/>
        public event GetOrderInfoPartCompletedEventHandler GetOrderInfoPartCompleted;
        
        /// <remarks/>
        public event GetOrderInfoCompletedEventHandler GetOrderInfoCompleted;
        
        /// <remarks/>
        public event GetkucunCompletedEventHandler GetkucunCompleted;
        
        /// <remarks/>
        public event kucunCompletedEventHandler kucunCompleted;
        
        /// <remarks/>
        public event GetorderNumCompletedEventHandler GetorderNumCompleted;
        
        /// <remarks/>
        public event GetOrderDeliveryPrintStateNewCompletedEventHandler GetOrderDeliveryPrintStateNewCompleted;
        
        /// <remarks/>
        public event DispatchListsInsertCompletedEventHandler DispatchListsInsertCompleted;
        
        /// <remarks/>
        public event CheckDeliveryNoCompletedEventHandler CheckDeliveryNoCompleted;
        
        /// <remarks/>
        public event GetByDeliveryNoCompletedEventHandler GetByDeliveryNoCompleted;
        
        /// <remarks/>
        public event LoginCheckCompletedEventHandler LoginCheckCompleted;
        
        /// <remarks/>
        public event DeupinhdCompletedEventHandler DeupinhdCompleted;
        
        /// <remarks/>
        public event RUserCompletedEventHandler RUserCompleted;
        
        /// <remarks/>
        public event GetHdNameAllCompletedEventHandler GetHdNameAllCompleted;
        
        /// <remarks/>
        public event GetPrintNumCompletedEventHandler GetPrintNumCompleted;
        
        /// <remarks/>
        public event GetTuanNumCompletedEventHandler GetTuanNumCompleted;
        
        /// <remarks/>
        public event GetWenTiDanCompletedEventHandler GetWenTiDanCompleted;
        
        /// <remarks/>
        public event UpWTdanCompletedEventHandler UpWTdanCompleted;
        
        /// <remarks/>
        public event GetHuiZongCompletedEventHandler GetHuiZongCompleted;
        
        /// <remarks/>
        public event CheckMergerOrderCompletedEventHandler CheckMergerOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNoKdTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetNoKdTable(string account, int count) {
            object[] results = this.Invoke("GetNoKdTable", new object[] {
                        account,
                        count});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetNoKdTableAsync(string account, int count) {
            this.GetNoKdTableAsync(account, count, null);
        }
        
        /// <remarks/>
        public void GetNoKdTableAsync(string account, int count, object userState) {
            if ((this.GetNoKdTableOperationCompleted == null)) {
                this.GetNoKdTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNoKdTableOperationCompleted);
            }
            this.InvokeAsync("GetNoKdTable", new object[] {
                        account,
                        count}, this.GetNoKdTableOperationCompleted, userState);
        }
        
        private void OnGetNoKdTableOperationCompleted(object arg) {
            if ((this.GetNoKdTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNoKdTableCompleted(this, new GetNoKdTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpKdFs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpKdFs(string tid, string kdfs) {
            object[] results = this.Invoke("UpKdFs", new object[] {
                        tid,
                        kdfs});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpKdFsAsync(string tid, string kdfs) {
            this.UpKdFsAsync(tid, kdfs, null);
        }
        
        /// <remarks/>
        public void UpKdFsAsync(string tid, string kdfs, object userState) {
            if ((this.UpKdFsOperationCompleted == null)) {
                this.UpKdFsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpKdFsOperationCompleted);
            }
            this.InvokeAsync("UpKdFs", new object[] {
                        tid,
                        kdfs}, this.UpKdFsOperationCompleted, userState);
        }
        
        private void OnUpKdFsOperationCompleted(object arg) {
            if ((this.UpKdFsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpKdFsCompleted(this, new UpKdFsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RealseLockuser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RealseLockuser(string ll) {
            object[] results = this.Invoke("RealseLockuser", new object[] {
                        ll});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RealseLockuserAsync(string ll) {
            this.RealseLockuserAsync(ll, null);
        }
        
        /// <remarks/>
        public void RealseLockuserAsync(string ll, object userState) {
            if ((this.RealseLockuserOperationCompleted == null)) {
                this.RealseLockuserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealseLockuserOperationCompleted);
            }
            this.InvokeAsync("RealseLockuser", new object[] {
                        ll}, this.RealseLockuserOperationCompleted, userState);
        }
        
        private void OnRealseLockuserOperationCompleted(object arg) {
            if ((this.RealseLockuserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealseLockuserCompleted(this, new RealseLockuserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RealseLock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RealseLock(string ll) {
            object[] results = this.Invoke("RealseLock", new object[] {
                        ll});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RealseLockAsync(string ll) {
            this.RealseLockAsync(ll, null);
        }
        
        /// <remarks/>
        public void RealseLockAsync(string ll, object userState) {
            if ((this.RealseLockOperationCompleted == null)) {
                this.RealseLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealseLockOperationCompleted);
            }
            this.InvokeAsync("RealseLock", new object[] {
                        ll}, this.RealseLockOperationCompleted, userState);
        }
        
        private void OnRealseLockOperationCompleted(object arg) {
            if ((this.RealseLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealseLockCompleted(this, new RealseLockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrintGroupBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPrintGroupBy() {
            object[] results = this.Invoke("GetPrintGroupBy", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPrintGroupByAsync() {
            this.GetPrintGroupByAsync(null);
        }
        
        /// <remarks/>
        public void GetPrintGroupByAsync(object userState) {
            if ((this.GetPrintGroupByOperationCompleted == null)) {
                this.GetPrintGroupByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrintGroupByOperationCompleted);
            }
            this.InvokeAsync("GetPrintGroupBy", new object[0], this.GetPrintGroupByOperationCompleted, userState);
        }
        
        private void OnGetPrintGroupByOperationCompleted(object arg) {
            if ((this.GetPrintGroupByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrintGroupByCompleted(this, new GetPrintGroupByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrintPart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPrintPart(int from, string orderunm, string kddh, string mjid, string caozuo, System.DateTime shijian, string hdname, System.DateTime ddtime, bool pt, bool dt) {
            object[] results = this.Invoke("GetPrintPart", new object[] {
                        from,
                        orderunm,
                        kddh,
                        mjid,
                        caozuo,
                        shijian,
                        hdname,
                        ddtime,
                        pt,
                        dt});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPrintPartAsync(int from, string orderunm, string kddh, string mjid, string caozuo, System.DateTime shijian, string hdname, System.DateTime ddtime, bool pt, bool dt) {
            this.GetPrintPartAsync(from, orderunm, kddh, mjid, caozuo, shijian, hdname, ddtime, pt, dt, null);
        }
        
        /// <remarks/>
        public void GetPrintPartAsync(int from, string orderunm, string kddh, string mjid, string caozuo, System.DateTime shijian, string hdname, System.DateTime ddtime, bool pt, bool dt, object userState) {
            if ((this.GetPrintPartOperationCompleted == null)) {
                this.GetPrintPartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrintPartOperationCompleted);
            }
            this.InvokeAsync("GetPrintPart", new object[] {
                        from,
                        orderunm,
                        kddh,
                        mjid,
                        caozuo,
                        shijian,
                        hdname,
                        ddtime,
                        pt,
                        dt}, this.GetPrintPartOperationCompleted, userState);
        }
        
        private void OnGetPrintPartOperationCompleted(object arg) {
            if ((this.GetPrintPartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrintPartCompleted(this, new GetPrintPartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderInfo2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOrderInfo2(string id) {
            object[] results = this.Invoke("GetOrderInfo2", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderInfo2Async(string id) {
            this.GetOrderInfo2Async(id, null);
        }
        
        /// <remarks/>
        public void GetOrderInfo2Async(string id, object userState) {
            if ((this.GetOrderInfo2OperationCompleted == null)) {
                this.GetOrderInfo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderInfo2OperationCompleted);
            }
            this.InvokeAsync("GetOrderInfo2", new object[] {
                        id}, this.GetOrderInfo2OperationCompleted, userState);
        }
        
        private void OnGetOrderInfo2OperationCompleted(object arg) {
            if ((this.GetOrderInfo2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderInfo2Completed(this, new GetOrderInfo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderInfoPart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrderInfoPart(string id) {
            object[] results = this.Invoke("GetOrderInfoPart", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderInfoPartAsync(string id) {
            this.GetOrderInfoPartAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOrderInfoPartAsync(string id, object userState) {
            if ((this.GetOrderInfoPartOperationCompleted == null)) {
                this.GetOrderInfoPartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderInfoPartOperationCompleted);
            }
            this.InvokeAsync("GetOrderInfoPart", new object[] {
                        id}, this.GetOrderInfoPartOperationCompleted, userState);
        }
        
        private void OnGetOrderInfoPartOperationCompleted(object arg) {
            if ((this.GetOrderInfoPartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderInfoPartCompleted(this, new GetOrderInfoPartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrderInfo(string id) {
            object[] results = this.Invoke("GetOrderInfo", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderInfoAsync(string id) {
            this.GetOrderInfoAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOrderInfoAsync(string id, object userState) {
            if ((this.GetOrderInfoOperationCompleted == null)) {
                this.GetOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderInfoOperationCompleted);
            }
            this.InvokeAsync("GetOrderInfo", new object[] {
                        id}, this.GetOrderInfoOperationCompleted, userState);
        }
        
        private void OnGetOrderInfoOperationCompleted(object arg) {
            if ((this.GetOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderInfoCompleted(this, new GetOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Getkucun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Getkucun(string sellename, string hdname, string time, string isclose) {
            object[] results = this.Invoke("Getkucun", new object[] {
                        sellename,
                        hdname,
                        time,
                        isclose});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetkucunAsync(string sellename, string hdname, string time, string isclose) {
            this.GetkucunAsync(sellename, hdname, time, isclose, null);
        }
        
        /// <remarks/>
        public void GetkucunAsync(string sellename, string hdname, string time, string isclose, object userState) {
            if ((this.GetkucunOperationCompleted == null)) {
                this.GetkucunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetkucunOperationCompleted);
            }
            this.InvokeAsync("Getkucun", new object[] {
                        sellename,
                        hdname,
                        time,
                        isclose}, this.GetkucunOperationCompleted, userState);
        }
        
        private void OnGetkucunOperationCompleted(object arg) {
            if ((this.GetkucunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetkucunCompleted(this, new GetkucunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/kucun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable kucun(string code) {
            object[] results = this.Invoke("kucun", new object[] {
                        code});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void kucunAsync(string code) {
            this.kucunAsync(code, null);
        }
        
        /// <remarks/>
        public void kucunAsync(string code, object userState) {
            if ((this.kucunOperationCompleted == null)) {
                this.kucunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnkucunOperationCompleted);
            }
            this.InvokeAsync("kucun", new object[] {
                        code}, this.kucunOperationCompleted, userState);
        }
        
        private void OnkucunOperationCompleted(object arg) {
            if ((this.kucunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.kucunCompleted(this, new kucunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetorderNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetorderNum(string sellename, string hdname, string time) {
            object[] results = this.Invoke("GetorderNum", new object[] {
                        sellename,
                        hdname,
                        time});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetorderNumAsync(string sellename, string hdname, string time) {
            this.GetorderNumAsync(sellename, hdname, time, null);
        }
        
        /// <remarks/>
        public void GetorderNumAsync(string sellename, string hdname, string time, object userState) {
            if ((this.GetorderNumOperationCompleted == null)) {
                this.GetorderNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetorderNumOperationCompleted);
            }
            this.InvokeAsync("GetorderNum", new object[] {
                        sellename,
                        hdname,
                        time}, this.GetorderNumOperationCompleted, userState);
        }
        
        private void OnGetorderNumOperationCompleted(object arg) {
            if ((this.GetorderNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetorderNumCompleted(this, new GetorderNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderDeliveryPrintStateNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrderDeliveryPrintStateNew(string account, string ShippingMethods, string orderNo, string category, string salestype, int count, string sellernick, string hdname) {
            object[] results = this.Invoke("GetOrderDeliveryPrintStateNew", new object[] {
                        account,
                        ShippingMethods,
                        orderNo,
                        category,
                        salestype,
                        count,
                        sellernick,
                        hdname});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderDeliveryPrintStateNewAsync(string account, string ShippingMethods, string orderNo, string category, string salestype, int count, string sellernick, string hdname) {
            this.GetOrderDeliveryPrintStateNewAsync(account, ShippingMethods, orderNo, category, salestype, count, sellernick, hdname, null);
        }
        
        /// <remarks/>
        public void GetOrderDeliveryPrintStateNewAsync(string account, string ShippingMethods, string orderNo, string category, string salestype, int count, string sellernick, string hdname, object userState) {
            if ((this.GetOrderDeliveryPrintStateNewOperationCompleted == null)) {
                this.GetOrderDeliveryPrintStateNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderDeliveryPrintStateNewOperationCompleted);
            }
            this.InvokeAsync("GetOrderDeliveryPrintStateNew", new object[] {
                        account,
                        ShippingMethods,
                        orderNo,
                        category,
                        salestype,
                        count,
                        sellernick,
                        hdname}, this.GetOrderDeliveryPrintStateNewOperationCompleted, userState);
        }
        
        private void OnGetOrderDeliveryPrintStateNewOperationCompleted(object arg) {
            if ((this.GetOrderDeliveryPrintStateNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderDeliveryPrintStateNewCompleted(this, new GetOrderDeliveryPrintStateNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DispatchListsInsert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DispatchListsInsert(string delivery, string csoCode, bool cf) {
            object[] results = this.Invoke("DispatchListsInsert", new object[] {
                        delivery,
                        csoCode,
                        cf});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DispatchListsInsertAsync(string delivery, string csoCode, bool cf) {
            this.DispatchListsInsertAsync(delivery, csoCode, cf, null);
        }
        
        /// <remarks/>
        public void DispatchListsInsertAsync(string delivery, string csoCode, bool cf, object userState) {
            if ((this.DispatchListsInsertOperationCompleted == null)) {
                this.DispatchListsInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDispatchListsInsertOperationCompleted);
            }
            this.InvokeAsync("DispatchListsInsert", new object[] {
                        delivery,
                        csoCode,
                        cf}, this.DispatchListsInsertOperationCompleted, userState);
        }
        
        private void OnDispatchListsInsertOperationCompleted(object arg) {
            if ((this.DispatchListsInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DispatchListsInsertCompleted(this, new DispatchListsInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDeliveryNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckDeliveryNo(string deliveryNo) {
            object[] results = this.Invoke("CheckDeliveryNo", new object[] {
                        deliveryNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDeliveryNoAsync(string deliveryNo) {
            this.CheckDeliveryNoAsync(deliveryNo, null);
        }
        
        /// <remarks/>
        public void CheckDeliveryNoAsync(string deliveryNo, object userState) {
            if ((this.CheckDeliveryNoOperationCompleted == null)) {
                this.CheckDeliveryNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDeliveryNoOperationCompleted);
            }
            this.InvokeAsync("CheckDeliveryNo", new object[] {
                        deliveryNo}, this.CheckDeliveryNoOperationCompleted, userState);
        }
        
        private void OnCheckDeliveryNoOperationCompleted(object arg) {
            if ((this.CheckDeliveryNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDeliveryNoCompleted(this, new CheckDeliveryNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByDeliveryNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetByDeliveryNo(string deliveryNo) {
            object[] results = this.Invoke("GetByDeliveryNo", new object[] {
                        deliveryNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetByDeliveryNoAsync(string deliveryNo) {
            this.GetByDeliveryNoAsync(deliveryNo, null);
        }
        
        /// <remarks/>
        public void GetByDeliveryNoAsync(string deliveryNo, object userState) {
            if ((this.GetByDeliveryNoOperationCompleted == null)) {
                this.GetByDeliveryNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByDeliveryNoOperationCompleted);
            }
            this.InvokeAsync("GetByDeliveryNo", new object[] {
                        deliveryNo}, this.GetByDeliveryNoOperationCompleted, userState);
        }
        
        private void OnGetByDeliveryNoOperationCompleted(object arg) {
            if ((this.GetByDeliveryNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByDeliveryNoCompleted(this, new GetByDeliveryNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoginCheck(string userNum, string password) {
            object[] results = this.Invoke("LoginCheck", new object[] {
                        userNum,
                        password});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoginCheckAsync(string userNum, string password) {
            this.LoginCheckAsync(userNum, password, null);
        }
        
        /// <remarks/>
        public void LoginCheckAsync(string userNum, string password, object userState) {
            if ((this.LoginCheckOperationCompleted == null)) {
                this.LoginCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginCheckOperationCompleted);
            }
            this.InvokeAsync("LoginCheck", new object[] {
                        userNum,
                        password}, this.LoginCheckOperationCompleted, userState);
        }
        
        private void OnLoginCheckOperationCompleted(object arg) {
            if ((this.LoginCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCheckCompleted(this, new LoginCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Deupinhd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Deupinhd(string hdname, string seller, string code, string title, string Seller_ID, string cfg, string oldhdname, string oldseller, string odlcode, string oldtitle) {
            object[] results = this.Invoke("Deupinhd", new object[] {
                        hdname,
                        seller,
                        code,
                        title,
                        Seller_ID,
                        cfg,
                        oldhdname,
                        oldseller,
                        odlcode,
                        oldtitle});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeupinhdAsync(string hdname, string seller, string code, string title, string Seller_ID, string cfg, string oldhdname, string oldseller, string odlcode, string oldtitle) {
            this.DeupinhdAsync(hdname, seller, code, title, Seller_ID, cfg, oldhdname, oldseller, odlcode, oldtitle, null);
        }
        
        /// <remarks/>
        public void DeupinhdAsync(string hdname, string seller, string code, string title, string Seller_ID, string cfg, string oldhdname, string oldseller, string odlcode, string oldtitle, object userState) {
            if ((this.DeupinhdOperationCompleted == null)) {
                this.DeupinhdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeupinhdOperationCompleted);
            }
            this.InvokeAsync("Deupinhd", new object[] {
                        hdname,
                        seller,
                        code,
                        title,
                        Seller_ID,
                        cfg,
                        oldhdname,
                        oldseller,
                        odlcode,
                        oldtitle}, this.DeupinhdOperationCompleted, userState);
        }
        
        private void OnDeupinhdOperationCompleted(object arg) {
            if ((this.DeupinhdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeupinhdCompleted(this, new DeupinhdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RUser(string a, string p, [System.Xml.Serialization.XmlElementAttribute("ruser")] string ruser1) {
            object[] results = this.Invoke("RUser", new object[] {
                        a,
                        p,
                        ruser1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RUserAsync(string a, string p, string ruser1) {
            this.RUserAsync(a, p, ruser1, null);
        }
        
        /// <remarks/>
        public void RUserAsync(string a, string p, string ruser1, object userState) {
            if ((this.RUserOperationCompleted == null)) {
                this.RUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRUserOperationCompleted);
            }
            this.InvokeAsync("RUser", new object[] {
                        a,
                        p,
                        ruser1}, this.RUserOperationCompleted, userState);
        }
        
        private void OnRUserOperationCompleted(object arg) {
            if ((this.RUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RUserCompleted(this, new RUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHdNameAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetHdNameAll(string Seller_ID) {
            object[] results = this.Invoke("GetHdNameAll", new object[] {
                        Seller_ID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetHdNameAllAsync(string Seller_ID) {
            this.GetHdNameAllAsync(Seller_ID, null);
        }
        
        /// <remarks/>
        public void GetHdNameAllAsync(string Seller_ID, object userState) {
            if ((this.GetHdNameAllOperationCompleted == null)) {
                this.GetHdNameAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHdNameAllOperationCompleted);
            }
            this.InvokeAsync("GetHdNameAll", new object[] {
                        Seller_ID}, this.GetHdNameAllOperationCompleted, userState);
        }
        
        private void OnGetHdNameAllOperationCompleted(object arg) {
            if ((this.GetHdNameAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHdNameAllCompleted(this, new GetHdNameAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrintNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetPrintNum(string username, string hdname) {
            object[] results = this.Invoke("GetPrintNum", new object[] {
                        username,
                        hdname});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPrintNumAsync(string username, string hdname) {
            this.GetPrintNumAsync(username, hdname, null);
        }
        
        /// <remarks/>
        public void GetPrintNumAsync(string username, string hdname, object userState) {
            if ((this.GetPrintNumOperationCompleted == null)) {
                this.GetPrintNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrintNumOperationCompleted);
            }
            this.InvokeAsync("GetPrintNum", new object[] {
                        username,
                        hdname}, this.GetPrintNumOperationCompleted, userState);
        }
        
        private void OnGetPrintNumOperationCompleted(object arg) {
            if ((this.GetPrintNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrintNumCompleted(this, new GetPrintNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTuanNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetTuanNum(System.DateTime dtime) {
            object[] results = this.Invoke("GetTuanNum", new object[] {
                        dtime});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTuanNumAsync(System.DateTime dtime) {
            this.GetTuanNumAsync(dtime, null);
        }
        
        /// <remarks/>
        public void GetTuanNumAsync(System.DateTime dtime, object userState) {
            if ((this.GetTuanNumOperationCompleted == null)) {
                this.GetTuanNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTuanNumOperationCompleted);
            }
            this.InvokeAsync("GetTuanNum", new object[] {
                        dtime}, this.GetTuanNumOperationCompleted, userState);
        }
        
        private void OnGetTuanNumOperationCompleted(object arg) {
            if ((this.GetTuanNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTuanNumCompleted(this, new GetTuanNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWenTiDan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetWenTiDan(System.DateTime dtime) {
            object[] results = this.Invoke("GetWenTiDan", new object[] {
                        dtime});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetWenTiDanAsync(System.DateTime dtime) {
            this.GetWenTiDanAsync(dtime, null);
        }
        
        /// <remarks/>
        public void GetWenTiDanAsync(System.DateTime dtime, object userState) {
            if ((this.GetWenTiDanOperationCompleted == null)) {
                this.GetWenTiDanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWenTiDanOperationCompleted);
            }
            this.InvokeAsync("GetWenTiDan", new object[] {
                        dtime}, this.GetWenTiDanOperationCompleted, userState);
        }
        
        private void OnGetWenTiDanOperationCompleted(object arg) {
            if ((this.GetWenTiDanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWenTiDanCompleted(this, new GetWenTiDanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpWTdan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpWTdan(string tid, string lx) {
            object[] results = this.Invoke("UpWTdan", new object[] {
                        tid,
                        lx});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpWTdanAsync(string tid, string lx) {
            this.UpWTdanAsync(tid, lx, null);
        }
        
        /// <remarks/>
        public void UpWTdanAsync(string tid, string lx, object userState) {
            if ((this.UpWTdanOperationCompleted == null)) {
                this.UpWTdanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpWTdanOperationCompleted);
            }
            this.InvokeAsync("UpWTdan", new object[] {
                        tid,
                        lx}, this.UpWTdanOperationCompleted, userState);
        }
        
        private void OnUpWTdanOperationCompleted(object arg) {
            if ((this.UpWTdanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpWTdanCompleted(this, new UpWTdanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHuiZong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetHuiZong(int address, System.DateTime dt) {
            object[] results = this.Invoke("GetHuiZong", new object[] {
                        address,
                        dt});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetHuiZongAsync(int address, System.DateTime dt) {
            this.GetHuiZongAsync(address, dt, null);
        }
        
        /// <remarks/>
        public void GetHuiZongAsync(int address, System.DateTime dt, object userState) {
            if ((this.GetHuiZongOperationCompleted == null)) {
                this.GetHuiZongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHuiZongOperationCompleted);
            }
            this.InvokeAsync("GetHuiZong", new object[] {
                        address,
                        dt}, this.GetHuiZongOperationCompleted, userState);
        }
        
        private void OnGetHuiZongOperationCompleted(object arg) {
            if ((this.GetHuiZongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHuiZongCompleted(this, new GetHuiZongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("myheaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckMergerOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckMergerOrder(string orderNo) {
            object[] results = this.Invoke("CheckMergerOrder", new object[] {
                        orderNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckMergerOrderAsync(string orderNo) {
            this.CheckMergerOrderAsync(orderNo, null);
        }
        
        /// <remarks/>
        public void CheckMergerOrderAsync(string orderNo, object userState) {
            if ((this.CheckMergerOrderOperationCompleted == null)) {
                this.CheckMergerOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckMergerOrderOperationCompleted);
            }
            this.InvokeAsync("CheckMergerOrder", new object[] {
                        orderNo}, this.CheckMergerOrderOperationCompleted, userState);
        }
        
        private void OnCheckMergerOrderOperationCompleted(object arg) {
            if ((this.CheckMergerOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckMergerOrderCompleted(this, new CheckMergerOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class myheader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetNoKdTableCompletedEventHandler(object sender, GetNoKdTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNoKdTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNoKdTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void UpKdFsCompletedEventHandler(object sender, UpKdFsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpKdFsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpKdFsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RealseLockuserCompletedEventHandler(object sender, RealseLockuserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealseLockuserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealseLockuserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RealseLockCompletedEventHandler(object sender, RealseLockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealseLockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealseLockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetPrintGroupByCompletedEventHandler(object sender, GetPrintGroupByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrintGroupByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrintGroupByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetPrintPartCompletedEventHandler(object sender, GetPrintPartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrintPartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrintPartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetOrderInfo2CompletedEventHandler(object sender, GetOrderInfo2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderInfo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderInfo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetOrderInfoPartCompletedEventHandler(object sender, GetOrderInfoPartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderInfoPartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderInfoPartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetOrderInfoCompletedEventHandler(object sender, GetOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetkucunCompletedEventHandler(object sender, GetkucunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetkucunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetkucunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void kucunCompletedEventHandler(object sender, kucunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class kucunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal kucunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetorderNumCompletedEventHandler(object sender, GetorderNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetorderNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetorderNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetOrderDeliveryPrintStateNewCompletedEventHandler(object sender, GetOrderDeliveryPrintStateNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderDeliveryPrintStateNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderDeliveryPrintStateNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void DispatchListsInsertCompletedEventHandler(object sender, DispatchListsInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DispatchListsInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DispatchListsInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void CheckDeliveryNoCompletedEventHandler(object sender, CheckDeliveryNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDeliveryNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDeliveryNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetByDeliveryNoCompletedEventHandler(object sender, GetByDeliveryNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByDeliveryNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByDeliveryNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void LoginCheckCompletedEventHandler(object sender, LoginCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void DeupinhdCompletedEventHandler(object sender, DeupinhdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeupinhdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeupinhdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RUserCompletedEventHandler(object sender, RUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetHdNameAllCompletedEventHandler(object sender, GetHdNameAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHdNameAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHdNameAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetPrintNumCompletedEventHandler(object sender, GetPrintNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrintNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrintNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetTuanNumCompletedEventHandler(object sender, GetTuanNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTuanNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTuanNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetWenTiDanCompletedEventHandler(object sender, GetWenTiDanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWenTiDanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWenTiDanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void UpWTdanCompletedEventHandler(object sender, UpWTdanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpWTdanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpWTdanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetHuiZongCompletedEventHandler(object sender, GetHuiZongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHuiZongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHuiZongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void CheckMergerOrderCompletedEventHandler(object sender, CheckMergerOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckMergerOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckMergerOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591