#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="double12")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProductOrderInfo(ProductOrderInfo instance);
    partial void UpdateProductOrderInfo(ProductOrderInfo instance);
    partial void DeleteProductOrderInfo(ProductOrderInfo instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ServiceLib.Properties.Settings.Default.double12ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProductOrderInfo> ProductOrderInfo
		{
			get
			{
				return this.GetTable<ProductOrderInfo>();
			}
		}
		
		public System.Data.Linq.Table<NMLCH_vUseNum> NMLCH_vUseNum
		{
			get
			{
				return this.GetTable<NMLCH_vUseNum>();
			}
		}
	}
	
	[Table(Name="dbo.ProductOrderInfo")]
	public partial class ProductOrderInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Seller_nick;
		
		private string _Buyer_nick;
		
		private string _Iid;
		
		private string _Title;
		
		private string _Price;
		
		private string _pic_path;
		
		private System.Nullable<int> _Num;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _Type;
		
		private string _Tid;
		
		private string _Alipay_no;
		
		private string _Payment;
		
		private string _Status;
		
		private string _Seller_rate;
		
		private string _Buyer_rate;
		
		private string _PaymentTime;
		
		private System.Nullable<bool> _IsError;
		
		private System.Nullable<bool> _IsComplete;
		
		private string _Consignee;
		
		private string _Phone;
		
		private string _Tel;
		
		private string _Provinces;
		
		private string _City;
		
		private string _District;
		
		private string _Address;
		
		private string _PostBack;
		
		private string _ExpressWay;
		
		private string _LogisticsCompanies;
		
		private string _AWBNo;
		
		private string _Remark;
		
		private System.Nullable<bool> _IsMerger;
		
		private System.Nullable<bool> _IsModifiedPostage;
		
		private string _JHLockUser;
		
		private string _freight;
		
		private string _PaymentTotal;
		
		private System.Nullable<bool> _IsClose;
		
		private string _buyMailBox;
		
		private System.Nullable<char> _salesType;
		
		private System.Nullable<System.DateTime> _addTime;
		
		private string _addType;
		
		private System.Nullable<bool> _Piecesday;
		
		private string _paymentmethod;
		
		private string _Paccount;
		
		private string _Pcode;
		
		private System.Nullable<bool> _IsRead;
		
		private System.Nullable<bool> _IsPrint;
		
		private System.Nullable<System.DateTime> _Stime;
		
		private System.Nullable<System.DateTime> _Ptime;
		
		private string _DeliveryNo;
		
		private string _hdname;
		
		private System.Nullable<int> _cfprint;
		
		private string _rongyu1;
		
		private string _rongyu2;
		
		private System.Nullable<bool> _rongyu3;
		
		private System.Nullable<bool> _rongyu4;
		
		private System.Nullable<int> _rongyu5;
		
		private System.Nullable<int> _rongyu6;
		
		private System.Nullable<System.DateTime> _rongyu7;
		
		private System.Nullable<System.DateTime> _rongyu8;
		
		private string _Memo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnSeller_nickChanging(string value);
    partial void OnSeller_nickChanged();
    partial void OnBuyer_nickChanging(string value);
    partial void OnBuyer_nickChanged();
    partial void OnIidChanging(string value);
    partial void OnIidChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void Onpic_pathChanging(string value);
    partial void Onpic_pathChanged();
    partial void OnNumChanging(System.Nullable<int> value);
    partial void OnNumChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnTidChanging(string value);
    partial void OnTidChanged();
    partial void OnAlipay_noChanging(string value);
    partial void OnAlipay_noChanged();
    partial void OnPaymentChanging(string value);
    partial void OnPaymentChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnSeller_rateChanging(string value);
    partial void OnSeller_rateChanged();
    partial void OnBuyer_rateChanging(string value);
    partial void OnBuyer_rateChanged();
    partial void OnPaymentTimeChanging(string value);
    partial void OnPaymentTimeChanged();
    partial void OnIsErrorChanging(System.Nullable<bool> value);
    partial void OnIsErrorChanged();
    partial void OnIsCompleteChanging(System.Nullable<bool> value);
    partial void OnIsCompleteChanged();
    partial void OnConsigneeChanging(string value);
    partial void OnConsigneeChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnProvincesChanging(string value);
    partial void OnProvincesChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPostBackChanging(string value);
    partial void OnPostBackChanged();
    partial void OnExpressWayChanging(string value);
    partial void OnExpressWayChanged();
    partial void OnLogisticsCompaniesChanging(string value);
    partial void OnLogisticsCompaniesChanged();
    partial void OnAWBNoChanging(string value);
    partial void OnAWBNoChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnIsMergerChanging(System.Nullable<bool> value);
    partial void OnIsMergerChanged();
    partial void OnIsModifiedPostageChanging(System.Nullable<bool> value);
    partial void OnIsModifiedPostageChanged();
    partial void OnJHLockUserChanging(string value);
    partial void OnJHLockUserChanged();
    partial void OnfreightChanging(string value);
    partial void OnfreightChanged();
    partial void OnPaymentTotalChanging(string value);
    partial void OnPaymentTotalChanged();
    partial void OnIsCloseChanging(System.Nullable<bool> value);
    partial void OnIsCloseChanged();
    partial void OnbuyMailBoxChanging(string value);
    partial void OnbuyMailBoxChanged();
    partial void OnsalesTypeChanging(System.Nullable<char> value);
    partial void OnsalesTypeChanged();
    partial void OnaddTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnaddTimeChanged();
    partial void OnaddTypeChanging(string value);
    partial void OnaddTypeChanged();
    partial void OnPiecesdayChanging(System.Nullable<bool> value);
    partial void OnPiecesdayChanged();
    partial void OnpaymentmethodChanging(string value);
    partial void OnpaymentmethodChanged();
    partial void OnPaccountChanging(string value);
    partial void OnPaccountChanged();
    partial void OnPcodeChanging(string value);
    partial void OnPcodeChanged();
    partial void OnIsReadChanging(System.Nullable<bool> value);
    partial void OnIsReadChanged();
    partial void OnIsPrintChanging(System.Nullable<bool> value);
    partial void OnIsPrintChanged();
    partial void OnStimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStimeChanged();
    partial void OnPtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnPtimeChanged();
    partial void OnDeliveryNoChanging(string value);
    partial void OnDeliveryNoChanged();
    partial void OnhdnameChanging(string value);
    partial void OnhdnameChanged();
    partial void OncfprintChanging(System.Nullable<int> value);
    partial void OncfprintChanged();
    partial void Onrongyu1Changing(string value);
    partial void Onrongyu1Changed();
    partial void Onrongyu2Changing(string value);
    partial void Onrongyu2Changed();
    partial void Onrongyu3Changing(System.Nullable<bool> value);
    partial void Onrongyu3Changed();
    partial void Onrongyu4Changing(System.Nullable<bool> value);
    partial void Onrongyu4Changed();
    partial void Onrongyu5Changing(System.Nullable<int> value);
    partial void Onrongyu5Changed();
    partial void Onrongyu6Changing(System.Nullable<int> value);
    partial void Onrongyu6Changed();
    partial void Onrongyu7Changing(System.Nullable<System.DateTime> value);
    partial void Onrongyu7Changed();
    partial void Onrongyu8Changing(System.Nullable<System.DateTime> value);
    partial void Onrongyu8Changed();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    #endregion
		
		public ProductOrderInfo()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_Seller_nick", DbType="NVarChar(50)")]
		public string Seller_nick
		{
			get
			{
				return this._Seller_nick;
			}
			set
			{
				if ((this._Seller_nick != value))
				{
					this.OnSeller_nickChanging(value);
					this.SendPropertyChanging();
					this._Seller_nick = value;
					this.SendPropertyChanged("Seller_nick");
					this.OnSeller_nickChanged();
				}
			}
		}
		
		[Column(Storage="_Buyer_nick", DbType="NVarChar(50)")]
		public string Buyer_nick
		{
			get
			{
				return this._Buyer_nick;
			}
			set
			{
				if ((this._Buyer_nick != value))
				{
					this.OnBuyer_nickChanging(value);
					this.SendPropertyChanging();
					this._Buyer_nick = value;
					this.SendPropertyChanged("Buyer_nick");
					this.OnBuyer_nickChanged();
				}
			}
		}
		
		[Column(Storage="_Iid", DbType="NVarChar(50)")]
		public string Iid
		{
			get
			{
				return this._Iid;
			}
			set
			{
				if ((this._Iid != value))
				{
					this.OnIidChanging(value);
					this.SendPropertyChanging();
					this._Iid = value;
					this.SendPropertyChanged("Iid");
					this.OnIidChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Price", DbType="NVarChar(50)")]
		public string Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[Column(Storage="_pic_path", DbType="NVarChar(200)")]
		public string pic_path
		{
			get
			{
				return this._pic_path;
			}
			set
			{
				if ((this._pic_path != value))
				{
					this.Onpic_pathChanging(value);
					this.SendPropertyChanging();
					this._pic_path = value;
					this.SendPropertyChanged("pic_path");
					this.Onpic_pathChanged();
				}
			}
		}
		
		[Column(Storage="_Num", DbType="Int")]
		public System.Nullable<int> Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this.OnNumChanging(value);
					this.SendPropertyChanging();
					this._Num = value;
					this.SendPropertyChanged("Num");
					this.OnNumChanged();
				}
			}
		}
		
		[Column(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Tid", DbType="NVarChar(50)")]
		public string Tid
		{
			get
			{
				return this._Tid;
			}
			set
			{
				if ((this._Tid != value))
				{
					this.OnTidChanging(value);
					this.SendPropertyChanging();
					this._Tid = value;
					this.SendPropertyChanged("Tid");
					this.OnTidChanged();
				}
			}
		}
		
		[Column(Storage="_Alipay_no", DbType="NVarChar(50)")]
		public string Alipay_no
		{
			get
			{
				return this._Alipay_no;
			}
			set
			{
				if ((this._Alipay_no != value))
				{
					this.OnAlipay_noChanging(value);
					this.SendPropertyChanging();
					this._Alipay_no = value;
					this.SendPropertyChanged("Alipay_no");
					this.OnAlipay_noChanged();
				}
			}
		}
		
		[Column(Storage="_Payment", DbType="NVarChar(50)")]
		public string Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this.OnPaymentChanging(value);
					this.SendPropertyChanging();
					this._Payment = value;
					this.SendPropertyChanged("Payment");
					this.OnPaymentChanged();
				}
			}
		}
		
		[Column(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[Column(Storage="_Seller_rate", DbType="NVarChar(50)")]
		public string Seller_rate
		{
			get
			{
				return this._Seller_rate;
			}
			set
			{
				if ((this._Seller_rate != value))
				{
					this.OnSeller_rateChanging(value);
					this.SendPropertyChanging();
					this._Seller_rate = value;
					this.SendPropertyChanged("Seller_rate");
					this.OnSeller_rateChanged();
				}
			}
		}
		
		[Column(Storage="_Buyer_rate", DbType="NVarChar(50)")]
		public string Buyer_rate
		{
			get
			{
				return this._Buyer_rate;
			}
			set
			{
				if ((this._Buyer_rate != value))
				{
					this.OnBuyer_rateChanging(value);
					this.SendPropertyChanging();
					this._Buyer_rate = value;
					this.SendPropertyChanged("Buyer_rate");
					this.OnBuyer_rateChanged();
				}
			}
		}
		
		[Column(Storage="_PaymentTime", DbType="NVarChar(50)")]
		public string PaymentTime
		{
			get
			{
				return this._PaymentTime;
			}
			set
			{
				if ((this._PaymentTime != value))
				{
					this.OnPaymentTimeChanging(value);
					this.SendPropertyChanging();
					this._PaymentTime = value;
					this.SendPropertyChanged("PaymentTime");
					this.OnPaymentTimeChanged();
				}
			}
		}
		
		[Column(Storage="_IsError", DbType="Bit")]
		public System.Nullable<bool> IsError
		{
			get
			{
				return this._IsError;
			}
			set
			{
				if ((this._IsError != value))
				{
					this.OnIsErrorChanging(value);
					this.SendPropertyChanging();
					this._IsError = value;
					this.SendPropertyChanged("IsError");
					this.OnIsErrorChanged();
				}
			}
		}
		
		[Column(Storage="_IsComplete", DbType="Bit")]
		public System.Nullable<bool> IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this.OnIsCompleteChanging(value);
					this.SendPropertyChanging();
					this._IsComplete = value;
					this.SendPropertyChanged("IsComplete");
					this.OnIsCompleteChanged();
				}
			}
		}
		
		[Column(Storage="_Consignee", DbType="NVarChar(50)")]
		public string Consignee
		{
			get
			{
				return this._Consignee;
			}
			set
			{
				if ((this._Consignee != value))
				{
					this.OnConsigneeChanging(value);
					this.SendPropertyChanging();
					this._Consignee = value;
					this.SendPropertyChanged("Consignee");
					this.OnConsigneeChanged();
				}
			}
		}
		
		[Column(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[Column(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[Column(Storage="_Provinces", DbType="NVarChar(50)")]
		public string Provinces
		{
			get
			{
				return this._Provinces;
			}
			set
			{
				if ((this._Provinces != value))
				{
					this.OnProvincesChanging(value);
					this.SendPropertyChanging();
					this._Provinces = value;
					this.SendPropertyChanged("Provinces");
					this.OnProvincesChanged();
				}
			}
		}
		
		[Column(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[Column(Storage="_District", DbType="NVarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[Column(Storage="_Address", DbType="NVarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[Column(Storage="_PostBack", DbType="NVarChar(50)")]
		public string PostBack
		{
			get
			{
				return this._PostBack;
			}
			set
			{
				if ((this._PostBack != value))
				{
					this.OnPostBackChanging(value);
					this.SendPropertyChanging();
					this._PostBack = value;
					this.SendPropertyChanged("PostBack");
					this.OnPostBackChanged();
				}
			}
		}
		
		[Column(Storage="_ExpressWay", DbType="NVarChar(50)")]
		public string ExpressWay
		{
			get
			{
				return this._ExpressWay;
			}
			set
			{
				if ((this._ExpressWay != value))
				{
					this.OnExpressWayChanging(value);
					this.SendPropertyChanging();
					this._ExpressWay = value;
					this.SendPropertyChanged("ExpressWay");
					this.OnExpressWayChanged();
				}
			}
		}
		
		[Column(Storage="_LogisticsCompanies", DbType="NVarChar(50)")]
		public string LogisticsCompanies
		{
			get
			{
				return this._LogisticsCompanies;
			}
			set
			{
				if ((this._LogisticsCompanies != value))
				{
					this.OnLogisticsCompaniesChanging(value);
					this.SendPropertyChanging();
					this._LogisticsCompanies = value;
					this.SendPropertyChanged("LogisticsCompanies");
					this.OnLogisticsCompaniesChanged();
				}
			}
		}
		
		[Column(Storage="_AWBNo", DbType="NVarChar(50)")]
		public string AWBNo
		{
			get
			{
				return this._AWBNo;
			}
			set
			{
				if ((this._AWBNo != value))
				{
					this.OnAWBNoChanging(value);
					this.SendPropertyChanging();
					this._AWBNo = value;
					this.SendPropertyChanged("AWBNo");
					this.OnAWBNoChanged();
				}
			}
		}
		
		[Column(Storage="_Remark", DbType="NVarChar(MAX)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[Column(Storage="_IsMerger", DbType="Bit")]
		public System.Nullable<bool> IsMerger
		{
			get
			{
				return this._IsMerger;
			}
			set
			{
				if ((this._IsMerger != value))
				{
					this.OnIsMergerChanging(value);
					this.SendPropertyChanging();
					this._IsMerger = value;
					this.SendPropertyChanged("IsMerger");
					this.OnIsMergerChanged();
				}
			}
		}
		
		[Column(Storage="_IsModifiedPostage", DbType="Bit")]
		public System.Nullable<bool> IsModifiedPostage
		{
			get
			{
				return this._IsModifiedPostage;
			}
			set
			{
				if ((this._IsModifiedPostage != value))
				{
					this.OnIsModifiedPostageChanging(value);
					this.SendPropertyChanging();
					this._IsModifiedPostage = value;
					this.SendPropertyChanged("IsModifiedPostage");
					this.OnIsModifiedPostageChanged();
				}
			}
		}
		
		[Column(Storage="_JHLockUser", DbType="VarChar(50)")]
		public string JHLockUser
		{
			get
			{
				return this._JHLockUser;
			}
			set
			{
				if ((this._JHLockUser != value))
				{
					this.OnJHLockUserChanging(value);
					this.SendPropertyChanging();
					this._JHLockUser = value;
					this.SendPropertyChanged("JHLockUser");
					this.OnJHLockUserChanged();
				}
			}
		}
		
		[Column(Storage="_freight", DbType="NVarChar(50)")]
		public string freight
		{
			get
			{
				return this._freight;
			}
			set
			{
				if ((this._freight != value))
				{
					this.OnfreightChanging(value);
					this.SendPropertyChanging();
					this._freight = value;
					this.SendPropertyChanged("freight");
					this.OnfreightChanged();
				}
			}
		}
		
		[Column(Storage="_PaymentTotal", DbType="NVarChar(50)")]
		public string PaymentTotal
		{
			get
			{
				return this._PaymentTotal;
			}
			set
			{
				if ((this._PaymentTotal != value))
				{
					this.OnPaymentTotalChanging(value);
					this.SendPropertyChanging();
					this._PaymentTotal = value;
					this.SendPropertyChanged("PaymentTotal");
					this.OnPaymentTotalChanged();
				}
			}
		}
		
		[Column(Storage="_IsClose", DbType="Bit")]
		public System.Nullable<bool> IsClose
		{
			get
			{
				return this._IsClose;
			}
			set
			{
				if ((this._IsClose != value))
				{
					this.OnIsCloseChanging(value);
					this.SendPropertyChanging();
					this._IsClose = value;
					this.SendPropertyChanged("IsClose");
					this.OnIsCloseChanged();
				}
			}
		}
		
		[Column(Storage="_buyMailBox", DbType="NVarChar(50)")]
		public string buyMailBox
		{
			get
			{
				return this._buyMailBox;
			}
			set
			{
				if ((this._buyMailBox != value))
				{
					this.OnbuyMailBoxChanging(value);
					this.SendPropertyChanging();
					this._buyMailBox = value;
					this.SendPropertyChanged("buyMailBox");
					this.OnbuyMailBoxChanged();
				}
			}
		}
		
		[Column(Storage="_salesType", DbType="Char(1)")]
		public System.Nullable<char> salesType
		{
			get
			{
				return this._salesType;
			}
			set
			{
				if ((this._salesType != value))
				{
					this.OnsalesTypeChanging(value);
					this.SendPropertyChanging();
					this._salesType = value;
					this.SendPropertyChanged("salesType");
					this.OnsalesTypeChanged();
				}
			}
		}
		
		[Column(Storage="_addTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> addTime
		{
			get
			{
				return this._addTime;
			}
			set
			{
				if ((this._addTime != value))
				{
					this.OnaddTimeChanging(value);
					this.SendPropertyChanging();
					this._addTime = value;
					this.SendPropertyChanged("addTime");
					this.OnaddTimeChanged();
				}
			}
		}
		
		[Column(Storage="_addType", DbType="VarChar(20)")]
		public string addType
		{
			get
			{
				return this._addType;
			}
			set
			{
				if ((this._addType != value))
				{
					this.OnaddTypeChanging(value);
					this.SendPropertyChanging();
					this._addType = value;
					this.SendPropertyChanged("addType");
					this.OnaddTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Piecesday", DbType="Bit")]
		public System.Nullable<bool> Piecesday
		{
			get
			{
				return this._Piecesday;
			}
			set
			{
				if ((this._Piecesday != value))
				{
					this.OnPiecesdayChanging(value);
					this.SendPropertyChanging();
					this._Piecesday = value;
					this.SendPropertyChanged("Piecesday");
					this.OnPiecesdayChanged();
				}
			}
		}
		
		[Column(Storage="_paymentmethod", DbType="NVarChar(50)")]
		public string paymentmethod
		{
			get
			{
				return this._paymentmethod;
			}
			set
			{
				if ((this._paymentmethod != value))
				{
					this.OnpaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._paymentmethod = value;
					this.SendPropertyChanged("paymentmethod");
					this.OnpaymentmethodChanged();
				}
			}
		}
		
		[Column(Storage="_Paccount", DbType="NVarChar(50)")]
		public string Paccount
		{
			get
			{
				return this._Paccount;
			}
			set
			{
				if ((this._Paccount != value))
				{
					this.OnPaccountChanging(value);
					this.SendPropertyChanging();
					this._Paccount = value;
					this.SendPropertyChanged("Paccount");
					this.OnPaccountChanged();
				}
			}
		}
		
		[Column(Storage="_Pcode", DbType="NVarChar(50)")]
		public string Pcode
		{
			get
			{
				return this._Pcode;
			}
			set
			{
				if ((this._Pcode != value))
				{
					this.OnPcodeChanging(value);
					this.SendPropertyChanging();
					this._Pcode = value;
					this.SendPropertyChanged("Pcode");
					this.OnPcodeChanged();
				}
			}
		}
		
		[Column(Storage="_IsRead", DbType="Bit")]
		public System.Nullable<bool> IsRead
		{
			get
			{
				return this._IsRead;
			}
			set
			{
				if ((this._IsRead != value))
				{
					this.OnIsReadChanging(value);
					this.SendPropertyChanging();
					this._IsRead = value;
					this.SendPropertyChanged("IsRead");
					this.OnIsReadChanged();
				}
			}
		}
		
		[Column(Storage="_IsPrint", DbType="Bit")]
		public System.Nullable<bool> IsPrint
		{
			get
			{
				return this._IsPrint;
			}
			set
			{
				if ((this._IsPrint != value))
				{
					this.OnIsPrintChanging(value);
					this.SendPropertyChanging();
					this._IsPrint = value;
					this.SendPropertyChanged("IsPrint");
					this.OnIsPrintChanged();
				}
			}
		}
		
		[Column(Storage="_Stime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Stime
		{
			get
			{
				return this._Stime;
			}
			set
			{
				if ((this._Stime != value))
				{
					this.OnStimeChanging(value);
					this.SendPropertyChanging();
					this._Stime = value;
					this.SendPropertyChanged("Stime");
					this.OnStimeChanged();
				}
			}
		}
		
		[Column(Storage="_Ptime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ptime
		{
			get
			{
				return this._Ptime;
			}
			set
			{
				if ((this._Ptime != value))
				{
					this.OnPtimeChanging(value);
					this.SendPropertyChanging();
					this._Ptime = value;
					this.SendPropertyChanged("Ptime");
					this.OnPtimeChanged();
				}
			}
		}
		
		[Column(Storage="_DeliveryNo", DbType="NVarChar(50)")]
		public string DeliveryNo
		{
			get
			{
				return this._DeliveryNo;
			}
			set
			{
				if ((this._DeliveryNo != value))
				{
					this.OnDeliveryNoChanging(value);
					this.SendPropertyChanging();
					this._DeliveryNo = value;
					this.SendPropertyChanged("DeliveryNo");
					this.OnDeliveryNoChanged();
				}
			}
		}
		
		[Column(Storage="_hdname", DbType="NVarChar(50)")]
		public string hdname
		{
			get
			{
				return this._hdname;
			}
			set
			{
				if ((this._hdname != value))
				{
					this.OnhdnameChanging(value);
					this.SendPropertyChanging();
					this._hdname = value;
					this.SendPropertyChanged("hdname");
					this.OnhdnameChanged();
				}
			}
		}
		
		[Column(Storage="_cfprint", DbType="Int")]
		public System.Nullable<int> cfprint
		{
			get
			{
				return this._cfprint;
			}
			set
			{
				if ((this._cfprint != value))
				{
					this.OncfprintChanging(value);
					this.SendPropertyChanging();
					this._cfprint = value;
					this.SendPropertyChanged("cfprint");
					this.OncfprintChanged();
				}
			}
		}
		
		[Column(Storage="_rongyu1", DbType="NVarChar(500)")]
		public string rongyu1
		{
			get
			{
				return this._rongyu1;
			}
			set
			{
				if ((this._rongyu1 != value))
				{
					this.Onrongyu1Changing(value);
					this.SendPropertyChanging();
					this._rongyu1 = value;
					this.SendPropertyChanged("rongyu1");
					this.Onrongyu1Changed();
				}
			}
		}
		
		[Column(Storage="_rongyu2", DbType="NVarChar(500)")]
		public string rongyu2
		{
			get
			{
				return this._rongyu2;
			}
			set
			{
				if ((this._rongyu2 != value))
				{
					this.Onrongyu2Changing(value);
					this.SendPropertyChanging();
					this._rongyu2 = value;
					this.SendPropertyChanged("rongyu2");
					this.Onrongyu2Changed();
				}
			}
		}
		
		[Column(Storage="_rongyu3", DbType="Bit")]
		public System.Nullable<bool> rongyu3
		{
			get
			{
				return this._rongyu3;
			}
			set
			{
				if ((this._rongyu3 != value))
				{
					this.Onrongyu3Changing(value);
					this.SendPropertyChanging();
					this._rongyu3 = value;
					this.SendPropertyChanged("rongyu3");
					this.Onrongyu3Changed();
				}
			}
		}
		
		[Column(Storage="_rongyu4", DbType="Bit")]
		public System.Nullable<bool> rongyu4
		{
			get
			{
				return this._rongyu4;
			}
			set
			{
				if ((this._rongyu4 != value))
				{
					this.Onrongyu4Changing(value);
					this.SendPropertyChanging();
					this._rongyu4 = value;
					this.SendPropertyChanged("rongyu4");
					this.Onrongyu4Changed();
				}
			}
		}
		
		[Column(Storage="_rongyu5", DbType="Int")]
		public System.Nullable<int> rongyu5
		{
			get
			{
				return this._rongyu5;
			}
			set
			{
				if ((this._rongyu5 != value))
				{
					this.Onrongyu5Changing(value);
					this.SendPropertyChanging();
					this._rongyu5 = value;
					this.SendPropertyChanged("rongyu5");
					this.Onrongyu5Changed();
				}
			}
		}
		
		[Column(Storage="_rongyu6", DbType="Int")]
		public System.Nullable<int> rongyu6
		{
			get
			{
				return this._rongyu6;
			}
			set
			{
				if ((this._rongyu6 != value))
				{
					this.Onrongyu6Changing(value);
					this.SendPropertyChanging();
					this._rongyu6 = value;
					this.SendPropertyChanged("rongyu6");
					this.Onrongyu6Changed();
				}
			}
		}
		
		[Column(Storage="_rongyu7", DbType="DateTime")]
		public System.Nullable<System.DateTime> rongyu7
		{
			get
			{
				return this._rongyu7;
			}
			set
			{
				if ((this._rongyu7 != value))
				{
					this.Onrongyu7Changing(value);
					this.SendPropertyChanging();
					this._rongyu7 = value;
					this.SendPropertyChanged("rongyu7");
					this.Onrongyu7Changed();
				}
			}
		}
		
		[Column(Storage="_rongyu8", DbType="DateTime")]
		public System.Nullable<System.DateTime> rongyu8
		{
			get
			{
				return this._rongyu8;
			}
			set
			{
				if ((this._rongyu8 != value))
				{
					this.Onrongyu8Changing(value);
					this.SendPropertyChanging();
					this._rongyu8 = value;
					this.SendPropertyChanged("rongyu8");
					this.Onrongyu8Changed();
				}
			}
		}
		
		[Column(Storage="_Memo", DbType="NVarChar(MAX)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.NMLCH_vUseNum")]
	public partial class NMLCH_vUseNum
	{
		
		private string _Stockcode;
		
		private string _StockName;
		
		private string _Color;
		
		private string _Size;
		
		private double _Amount;
		
		public NMLCH_vUseNum()
		{
		}
		
		[Column(Storage="_Stockcode", DbType="VarChar(20)")]
		public string Stockcode
		{
			get
			{
				return this._Stockcode;
			}
			set
			{
				if ((this._Stockcode != value))
				{
					this._Stockcode = value;
				}
			}
		}
		
		[Column(Storage="_StockName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StockName
		{
			get
			{
				return this._StockName;
			}
			set
			{
				if ((this._StockName != value))
				{
					this._StockName = value;
				}
			}
		}
		
		[Column(Storage="_Color", DbType="VarChar(MAX)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[Column(Storage="_Size", DbType="VarChar(MAX)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[Column(Storage="_Amount", DbType="Float NOT NULL")]
		public double Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
